local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Hi!", "Synapse")
local Tab = Window:NewTab("read me!")
local Section = Tab:NewSection("I will not take responsibility if you are banned.")
Section:NewLabel("For Damage multplying (dm) ")
Section:NewLabel("dm may not work on certain weapons")
Section:NewLabel("reload to a new mag ( Bolter ) if it stops dealing dmg")
Section:NewLabel("don't use Aerorig with dm")
Section:NewLabel("For Hitbox exetending (he) ")
Section:NewLabel("he may error due to it scan on unreal head")
Section:NewLabel("for example rangers or tanks")
Section:NewLabel("For Infinite ammo")
Section:NewLabel("I wouldn't recommend using it")
Section:NewLabel("RPG and Grenade launcher may/ may not work")
Section:NewLabel("If you read to here, thank you for paying attention")
Section:NewLabel("Have fun hacking, and u can know close this window.")
