local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Hi!", "Synapse")
local Tab = Window:NewTab("read me!")
local Section = Tab:NewSection("If you get banned, I will not be responsible for it.")
Section:NewLabel("For Damage multplying (dm) ")
Section:NewLabel("the damage multiplier will not always work on certain weapons")
Section:NewLabel("if you use bolter with dm, reload to a new mag if stop deal any dmg to enemies")
Section:NewLabel("don't use Aerorig with dm")
Section:NewLabel("For Hitbox exetending (he) ")
Section:NewLabel("he may error due to it scan on unreal head")
Section:NewLabel("for example rangers or tanks")
Section:NewLabel("For Infinite ammo")
Section:NewLabel("I wouldn't recommend using it but your choice")
Section:NewLabel("RPG and Grenade launcher may/ may not work")
Section:NewLabel("If you read to here, thank you for paying attention, have fun hacking!")
Section:NewLabel("You can know close this window.")
