local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("AMBATUKAMMMMMMMMMMM", "Synapse")
local Tab = Window:NewTab("OMG")
local Section = Tab:NewSection("AUGHHHHHHHHHHHHHHHHHHHH")
Section:NewButton("Hitbox", "ButtonInfo", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/IrishBaker/scripts/main/NvZ/Resource.lua'))()
end)
Section:NewButton("Item ESP", "ButtonInfo", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/IrishBaker/REWORK/main/Entry%20Point/searcher.lua'))()
end)
Section:NewButton("IY", "ButtonInfo", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/IrishBaker/REWORK/main/Misc/IY.lua'))()
end)
